### PR TITLE
fix: adds default styling for starsvg

### PR DESCRIPTION
**Pull request by jasonpraful**
Adds default styling (`display: inline`) to class star-svg to fix v4 bug which causes rating component to render stars vertically.

Reference Issue - #9 

Screenshot 2022-02-06 at 15 53 38

### CODE REVIEW

**Review by jorgemasta — APPROVED** [review]

**Comment by jasonpraful** [comment]
@awran5 - could we get this merged please

**Comment by mikiyasgirma** [comment]
yeah, merge it please

**Comment by awran5** [comment]
Thank you guys.

**Comment by iiaan** [comment]
I have no idea where the star-svg class is located.

**Comment by JohnyClash** [comment]
@iiaan Create a css class in the css file that controls the component using the Rating component. 
`.star-svg{
    display:inline
}
`

**Pull request merged**
